<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpRXMGq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpRXMGq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZpRXMGq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZpRXMGq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZpRXMGq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZpRXMGq',
    'container.build_id' => '467de6d0',
    'container.build_time' => 1598476576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpRXMGq');
