<?php

namespace ContainerZpRXMGq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1qHHxKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1qHHxK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1qHHxK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ticket' => ['privates', '.errored..service_locator.F1qHHxK.App\\Entity\\Ticket', NULL, 'Cannot autowire service ".service_locator.F1qHHxK": it references class "App\\Entity\\Ticket" but no such service exists.'],
            'userInterface' => ['privates', '.errored..service_locator.F1qHHxK.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.F1qHHxK": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'ticket' => 'App\\Entity\\Ticket',
            'userInterface' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
